org: jonvibes
service: document-analyzer-api

provider:
  name: aws
  region: us-east-1
  runtime: python3.11
  architecture: x86_64
  environment:
    BUCKET_NAME: !Ref UploadsBucket
    DOCUMENT_TABLE: !Ref DocumentTable
    CHAT_TABLE: !Ref ChatTable
    USER_TABLE: !Ref UserTable
    TEXTRACT_TOPIC_ARN: !Ref TextractTopic
    TEXTRACT_ROLE_ARN: !GetAtt TextractPublishRole.Arn
    JWT_PRIVATE_KEY: ${env:JWT_PRIVATE_KEY}
    JWT_PUBLIC_KEY: ${env:JWT_PUBLIC_KEY}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    NEON_DATABASE_URL: ${env:NEON_DATABASE_URL}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: !Sub "${UploadsBucket.Arn}/*"

        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - !GetAtt DocumentTable.Arn
            - !Sub "${DocumentTable.Arn}/index/*"
            - !GetAtt UserTable.Arn
            - !Sub "${UserTable.Arn}/index/*"

        - Effect: Allow
          Action:
            - textract:StartDocumentAnalysis
            - textract:GetDocumentAnalysis
          Resource: "*"

functions:
  createDocument:
    image:
      uri: ${env:ECR_IMAGE_URI}
      command:
        - src.functions.create_document.handler.handler
    events:
      - httpApi:
          path: /document
          method: POST

  signin:
    image:
      uri: ${env:ECR_IMAGE_URI}
      command:
        - src.functions.signin.handler.handler
    events:
      - httpApi:
          path: /signin
          method: POST

  signup:
    image:
      uri: ${env:ECR_IMAGE_URI}
      command:
        - src.functions.signup.handler.handler
    events:
      - httpApi:
          path: /signup
          method: POST

  startExtracting:
    image:
      uri: ${env:ECR_IMAGE_URI}
      command:
        - src.functions.start_extraction_text.handler.handler
    events:
      - eventBridge:
          pattern:
            source:
              - aws.s3
            detail-type:
              - Object Created
            detail:
              bucket:
                name:
                  - !Ref UploadsBucket
              object:
                key:
                  - wildcard: "*/raw/*"

  indexDocument:
    image:
      uri: ${env:ECR_IMAGE_URI}
      command:
        - src.functions.index_document.handler.handler
    events:
      - eventBridge:
          pattern:
            source:
              - aws.s3
            detail-type:
              - Object Created
            detail:
              bucket:
                name:
                  - !Ref UploadsBucket
              object:
                key:
                  - wildcard: "*/extracted/*"
    timeout: 15

  textractCompleted:
    image:
      uri: ${env:ECR_IMAGE_URI}
      command:
        - src.functions.textract_completed.handler.handler

  askQuestion:
    image:
      uri: ${env:ECR_IMAGE_URI}
      command:
        - src.functions.ask_question.handler.handler

  questionProcessing:
    image:
      uri: ${env:ECR_IMAGE_URI}
      command:
        - src.functions.question_processing.handler.handler
    events:
      - eventBridge:
          pattern:
            source:
              - docinsight.chat
            detail-type:
              - QuestionAsked
    timeout: 15

resources:
  Resources:
    TextractTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: textract-document-completed

    TextractPublishRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: textract-publish-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: textract.amazonaws.com
              Action: sts:AssumeRole

        Policies:
          - PolicyName: PublishToSNS
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - sns:Publish
                  Resource: !Ref TextractTopic

    TextractSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref TextractTopic
        Protocol: lambda
        Endpoint: !GetAtt TextractCompletedLambdaFunction.Arn

    TextractPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: !Ref TextractCompletedLambdaFunction
        Action: lambda:InvokeFunction
        Principal: sns.amazonaws.com
        SourceArn: !Ref TextractTopic

    UploadsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: docinsight-raw-documents
        NotificationConfiguration:
          EventBridgeConfiguration:
            EventBridgeEnabled: true

    DocumentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: document-table
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: s3_key
            AttributeType: S
          - AttributeName: textract_job_id
            AttributeType: S
          - AttributeName: extracted_text_key
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: storage-key-index
            KeySchema:
              - AttributeName: s3_key
                KeyType: HASH
            Projection:
              ProjectionType: ALL

          - IndexName: textract-job-id-index
            KeySchema:
              - AttributeName: textract_job_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL

          - IndexName: extracted-text-key-index
            KeySchema:
              - AttributeName: extracted_text_key
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: user-table
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: email-index
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    ChatTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: chat-table
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: conversation_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: document_id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: conversation-id-index
            KeySchema:
              - AttributeName: conversation_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL

          - IndexName: user-id-index
            KeySchema:
              - AttributeName: user_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL

          - IndexName: document-id-index
            KeySchema:
              - AttributeName: document_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
