org: jonvibes
service: document-analyzer-api

custom:
  pythonRequirements:
    dockerizePip: true

provider:
  name: aws
  region: us-east-1
  runtime: python3.11
  architecture: arm64
  environment:
    BUCKET_NAME: !Ref UploadsBucket
    DOCUMENT_TABLE: !Ref DocumentTable
    USER_TABLE: !Ref UserTable
    JWT_PRIVATE_KEY: ${env:JWT_PRIVATE_KEY}
    JWT_PUBLIC_KEY: ${env:JWT_PUBLIC_KEY}
    TEXTRACT_TOPIC_ARN: !Ref TextractTopic
    TEXTRACT_ROLE_ARN: !Getatt TextractPublishRole.Arn

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: !Sub "${UploadsBucket.Arn}/*"

        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - !GetAtt DocumentTable.Arn
            - !Sub "${DocumentTable.Arn}/index/*"
            - !GetAtt UserTable.Arn
            - !Sub "${UserTable.Arn}/index/*"

        - Effect: Allow
          Action:
            - textract:StartDocumentTextDetection
            - textract:GetDocumentTextDetection
          Resource: "*"

functions:
  createDocument:
    handler: src.functions.create_document.handler.handler
    events:
      - httpApi:
          path: /document
          method: POST

  signin:
    handler: src.functions.signin.handler.handler
    events:
      - httpApi:
          path: /signin
          method: POST

  signup:
    handler: src.functions.signup.handler.handler
    events:
      - httpApi:
          path: /signup
          method: POST

  startExtracting:
    handler: src.functions.document_processor.start_extraction_text.handler
    events:
      - eventBridge:
          pattern:
            source:
              - aws.s3
            detail-type:
              - Object Created
            detail:
              bucket:
                name:
                  - !Ref UploadsBucket
              object:
                key:
                  - wildcard: "*/raw/*"

  textractCompleted:
    handler: src.functions.document_processor.textract_completed.handler
    events:
      - sns:
          arn: !Ref TextractTopic

resources:
  Resources:
    TextractTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: textract-document-completed

    TextractPublishRole:
      Type: AWS::SNS::Role
      Properties:
        RoleName: textract-publish-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: textract.amazonaws.com
              Action: sts:AssumeRole

        Policies:
          - PolicyName: PublishToSNS
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - sns:Publish
                  Resource: !Ref TextractTopic

    UploadsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: docinsight-raw-documents
        NotificationConfiguration:
          EventBridgeConfiguration:
            EventBridgeEnabled: true

    DocumentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: document-table
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: s3_key
            AttributeType: S
          - AttributeName: textract_job_id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: storage-key-index
            KeySchema:
              - AttributeName: s3_key
                KeyType: HASH
            Projection:
              ProjectionType: ALL

          - IndexName: trextact-job-id
            KeySchema:
              - AttributeName: textract_job_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: user-table
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: email-index
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
